-- MySQL Script generated by MySQL Workbench
-- 03/23/17 16:39:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema AirBnb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `AirBnb` ;

-- -----------------------------------------------------
-- Schema AirBnb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AirBnb` ;
USE `AirBnb` ;

-- -----------------------------------------------------
-- Table `AirBnb`.`Proprietaire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AirBnb`.`Proprietaire` ;

CREATE TABLE IF NOT EXISTS `AirBnb`.`Proprietaire` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `telephone` VARCHAR(25) NULL,
  `email` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idProprietaire_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AirBnb`.`Adresse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AirBnb`.`Adresse` ;

CREATE TABLE IF NOT EXISTS `AirBnb`.`Adresse` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rue` VARCHAR(100) NULL,
  `code` VARCHAR(45) NULL,
  `ville` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idadresse_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AirBnb`.`TypeLogement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AirBnb`.`TypeLogement` ;

CREATE TABLE IF NOT EXISTS `AirBnb`.`TypeLogement` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AirBnb`.`Logement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AirBnb`.`Logement` ;

CREATE TABLE IF NOT EXISTS `AirBnb`.`Logement` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL,
  `adresse_id` INT NOT NULL,
  `Proprietaire_id` INT NOT NULL,
  `TypeLogement_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idLogement_UNIQUE` (`id` ASC),
  INDEX `fk_Logement_adresse1_idx` (`adresse_id` ASC),
  INDEX `fk_Logement_Proprietaire1_idx` (`Proprietaire_id` ASC),
  INDEX `fk_Logement_TypeLogement1_idx` (`TypeLogement_id` ASC),
  CONSTRAINT `fk_Logement_adresse1`
    FOREIGN KEY (`adresse_id`)
    REFERENCES `AirBnb`.`Adresse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Logement_Proprietaire1`
    FOREIGN KEY (`Proprietaire_id`)
    REFERENCES `AirBnb`.`Proprietaire` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Logement_TypeLogement1`
    FOREIGN KEY (`TypeLogement_id`)
    REFERENCES `AirBnb`.`TypeLogement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AirBnb`.`Disponibilite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AirBnb`.`Disponibilite` ;

CREATE TABLE IF NOT EXISTS `AirBnb`.`Disponibilite` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `debut` DATETIME NULL,
  `fin` DATETIME NULL,
  `Logement_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_disponibilite_Logement1_idx` (`Logement_id` ASC),
  CONSTRAINT `fk_disponibilite_Logement1`
    FOREIGN KEY (`Logement_id`)
    REFERENCES `AirBnb`.`Logement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
